wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 90]
  refreshInterval: 1
  mods:
    gitlab:
      apiKey: "dzj-oVzqkxYYXpjW7zsW"
      enabled: true
      position:
        top: 2
        left: 1
        height: 2
        width: 2
      projects:
        - "Unbabel/integrations-team/messages"
        - "Unbabel/integrations-team/slingshot"
        - "Unbabel/integrations-team/documents"
        - "Unbabel/sre-team/k8s-base"
      refreshInterval: 300
      username: "jose_correia"
    hackernews:
      enabled: true
      numberOfStories: 15
      position:
        top: 0
        left: 1
        height: 2
        width: 2
      storyType: top
      refreshInterval: 900
    #feedreader:
      #enabled: true
      #feeds:
      #- http://feeds.bbci.co.uk/news/rss.xml
      #feedLimit: 10
      #position:
        #top: 1
        #left: 1
        #width: 2
        #height: 1
      #refreshInterval: 14400
    resourceusage:
      cpuCombined: false
      enabled: true
      position:
        top: 0
        left: 0
        height: 2
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
