wtf:
  colors:
    border:
      focusable: darkslateblue
      focused: orange
      normal: gray
  grid:
    columns: [32, 32, 32, 32, 90]
    rows: [10, 10, 10, 4, 4, 10, 10, 20, 20]
  refreshInterval: 1
  mods:
    gcal:
      colors:
        title: "yellow"
        eventTime: "lightblue"
        description: "red"
        highlights:
        - ['1on1|1\/11', 'green']
        - ['apple|google|aws', 'blue']
        - ['interview|meet', 'magenta']
        - ['lunch', 'yellow']
        past: "gray"
      calendarReadLevel: "reader"
      conflictIcon: "🚨"
      currentIcon: "💥"
      displayResponseStatus: true
      email: "menesesjmmc@gmail.com"
      enabled: true
      eventCount: 15
      hourFormat: "12"
      multiCalendar: true
      position:
        top: 0
        left: 1
        height: 2
        width: 3
      refreshInterval: 300
      secretFile: "~/.config/wtf/gcal/client_secret.json"
      showDeclined: true
      showEndTime: false
      timezone: "Europe/Lisbon"
      withLocation: true
    hackernews:
      enabled: true
      numberOfStories: 16
      position:
        top: 2
        left: 1
        height: 3
        width: 3
      storyType: top
      refreshInterval: 900
    feedreader:
      enabled: true
      feeds:
        - https://rss.app/feeds/q4WCKoGa2Cx75qNz.xml
        - https://rss.app/feeds/Pv70YYP7QdGhmri6.xml
      feedLimit: 16
      position:
        top: 5
        left: 1
        height: 3
        width: 3
      refreshInterval: 300
    digitalclock:
      color: orange
      enabled: true
      font: bigfont
      hourFormat: 24
      position:
        top: 0
        left: 0
        height: 1
        width: 1
      refreshInterval: 1
      type: "digitalclock"
    prettyweather:
      enabled: true
      city: "lisbon"
      position:
          top: 1
          left: 0
          height: 1
          width: 1
      refreshInterval: 300
      unit: "m"
      view: 0
      language: "en"
    resourceusage:
      cpuCombined: true
      enabled: true
      position:
        top: 3
        left: 0
        height: 1
        width: 1
      refreshInterval: 1
      showCPU: true
      showMem: true
      showSwp: true
    ipinfo:
      colors:
        name: "lightblue"
        value: "white"
      enabled: true
      position:
        top: 4
        left: 0
        height: 1
        width: 1
      refreshInterval: 150
    power:
      enabled: true
      position:
        top: 2
        left: 0
        height: 1
        width: 1
      refreshInterval: 15
      title: "⚡️"
